Added Vim command for `create_element_from_path.py`
iqm-finland/KQCircuits pull request #55
Opened 2023-06-09 05:18 UTC by AVDiv

#48 
Added Vim/NeoVim command for `create_element_from_path.py` with instructions to setup.
Please notify if any changes are needed to be done.

2023-06-09 05:23 UTC, AVDiv commented
Hey, I just signed the CLA.

2023-06-09 06:29 UTC, qpavsmi commented
Thank you for your contribution! Will try out the instructions now and come back to you on approval or improvement ideas!

2023-06-09 12:11 UTC, qpavsmi commented
@cla-bot

2023-06-09 12:17 UTC, qpavsmi commented
> Thank you for your pull request and welcome to our community.
> 
> We require contributors to sign our Contributor License Agreement (CLA), and it seems that the following contributors have not yet signed it: @AVDiv.
> 
> **In order for us to review and merge your code, please [sign the CLA at meetiqm.com](https://meetiqm.com/developers/clas/)**.
> 
> Once you have signed the CLA, write a comment here and we'll verify. Please note that it may take some time for us to verify it.

Check

2023-06-09 12:22 UTC, qpavsmi commented
@cla-bot check

2023-06-10 11:12 UTC, AVDiv commented
Any improvements to be done? @qpavsmi

2023-06-10 11:51 UTC, qpavsmi requested changes

2023-06-10 11:51 UTC, qpavsmi commented on util/create_element_from_path.py
> +#
Great job on the instructions over all! Some notes after trying out the instructions:

```suggestion
# To use this as a macro command in Vim/NeoVim
#   1. Open your Vim or NeoVim configuration file.
#      
#      Linux/macOS:
#        * Vim: The configuration file is located at ~/.vimrc.
#        * NeoVim: The configuration file is located at ~/.config/nvim/init.vim.
#      Windows:
#        * Vim: The configuration file is located at $HOME/vimfiles/vimrc or $VIM/_vimrc. (These are default paths, Usually installed in this path unless changed upon installation)
#        * NeoVim: The configuration file is located at $HOME/AppData/Local/nvim/init.vim. (These are default paths, Usually installed in this path unless changed upon installation)
#
#        The configuration file may not be present, in which case you need to create one at a specified location.
#        Use the following command to verify that vim loaded the expected configuration file:
#            :e $MYVIMRC
#
#   2. Add the following lines to your configuration file:
#       " Define a kqc command
#       command! -nargs=0 Kqc execute "!klayout -e -rm {FULL PATH TO create_element_from_path.py} -rd element_path=" . expand("%:p") | redraw!
#       " Create a mapping to run the kqc command
#       nnoremap <leader>kqc :Kqc<CR>
#
#       After copy-pasting, substitute {FULL PATH TO create_element_from_path.py} with the absolute path to the util/create_element_from_path.py python script
#       On Windows, klayout command does not work automatically, in which case it is best to substitute klayout keyword with the expanded absolute path to %APPDATA%/KLayout/klayout_app.exe
#
#   3. Save the configuration file and restart Vim or NeoVim for the changes to take effect.
#       Now, you can use the mapping <leader>kqc (where <leader> is a customizable key, often \ by default) while editing a Python file containing the element to create. 
#       Pressing the mapping will execute the :kqc command, which runs the external tool command to open the file in KLayout.
#
```

1. It's good to mention that if the configuration file is not in the file system, then user should create it.
2. Apparently the command name should start with capital letter, otherwise for me it complained about trailing characters.
3. klayout command not recognized in windows, so added a comment to substitute that with the full path to klayout executable
4. create_element_from_path.py also better to instruct to configure using absolute path

This also requires a change in the create_element_from_path.py for it to be able to handle element_path if they are absolute paths (currently it only can handle them if their root is the KQCircuits project folder). Simply locate the code block

https://github.com/iqm-finland/KQCircuits/blob/6be40f6b7376fb39477bd86f30379c2fb0b637d7/util/create_element_from_path.py#L98

and replace it with

```
for idx, part in reversed(list(enumerate(path_without_extension.parts))):
    if 'Circuits' in part:
        path_without_extension = path_without_extension.relative_to(*path_without_extension.parts[:idx+1])
```

2023-06-10 11:51 UTC, qpavsmi commented on util/create_element_from_path.py
> +#
Above are proposed changes

2023-06-10 11:52 UTC, qpavsmi commented
> Any improvements to be done? @qpavsmi

Hi, sorry, I thought my review went public but apparently it didnt: https://github.com/iqm-finland/KQCircuits/pull/55#discussion_r1224041294

2023-06-10 13:52 UTC, AVDiv commented on util/create_element_from_path.py
> +#
Nice I'll check on that ASAP.

2023-06-10 13:53 UTC, AVDiv commented
> > Any improvements to be done? @qpavsmi
> 
> Hi, sorry, I thought my review went public but apparently it didnt: [#55 (comment)](https://github.com/iqm-finland/KQCircuits/pull/55#discussion_r1224041294)

No issues👍

2023-06-10 14:34 UTC, AVDiv commented
Right, done with it. Anything else to improve? @qpavsmi

2023-06-10 16:34 UTC, qpavsmi commented
> Right, done with it. Anything else to improve? @qpavsmi

Thank you for the update, will check it when I get home

2023-06-10 16:39 UTC, qpavsmi commented
> > Right, done with it. Anything else to improve? @qpavsmi
> 
> Thank you for the update, will check it when I get home

Looking at the diffs on my phone they look good, thank you! Please squash the three commits into one commit with a descriptive commit message (message for first commit was good enough).

2023-06-10 16:57 UTC, AVDiv commented
> > > Right, done with it. Anything else to improve? @qpavsmi
> > 
> > 
> > Thank you for the update, will check it when I get home
> 
> Looking at the diffs on my phone they look good, thank you! Please squash the three commits into one commit with a descriptive commit message (message for first commit was good enough). It will probably require force push.

Okay

2023-06-10 17:06 UTC, AVDiv commented
I think starting off with a new PR would be nice, right?

2023-06-10 17:10 UTC, qpavsmi commented
> I think starting off with a new PR would be nice, right?

Actually dont worry about

2023-06-10 17:15 UTC, AVDiv commented
> > I think starting off with a new PR would be nice, right?
> 
> Actually dont worry about

OK

2023-06-10 17:20 UTC, qpavsmi commented
> > > I think starting off with a new PR would be nice, right?
> > 
> > 
> > Actually dont worry about
> 
> OK

I updated the last message :) anyway you could check some static analysis failures (just pylint stuff) here: https://github.com/iqm-finland/KQCircuits/actions/runs/5231064161/jobs/9444987678?pr=55 some lines were too long, so those can be fixed before merge

2023-06-10 17:21 UTC, AVDiv commented
> > > > I think starting off with a new PR would be nice, right?
> > > 
> > > 
> > > Actually dont worry about
> > 
> > 
> > OK
> 
> I updated the last message :) anyway you could check some static analysis failures (just pylint stuff) here: https://github.com/iqm-finland/KQCircuits/actions/runs/5231064161/jobs/9444987678?pr=55 some lines were too long, so those can be fixed before merge

yep, just noticed it & now I'm fixing it.

2023-06-10 17:37 UTC, AVDiv commented
Right fixed those

2023-06-10 19:19 UTC, qpavsmi reviewed
Approving by comment, and will mark you as a receiver for the bounty. Depending on whether I'll have time tomorrow or early next week I will merge this as part of our official branch, there is a process for it and I need to be careful. Thank you very much for the contribution and good job!

2023-06-11 00:29 UTC, AVDiv commented
> Approving by comment, and will mark you as a receiver for the bounty. Depending on whether I'll have time tomorrow or early next week I will merge this as part of our official branch, there is a process for it and I need to be careful. Thank you very much for the contribution and good job!

Thank you, grateful to work with you.🙌

2023-06-12 05:41 UTC, AVDiv commented
hi @qpavsmi ,
Can you also mark the issue as done on [unitaryhack](https://unitaryhack.dev)

2023-06-12 05:45 UTC, qpavsmi commented
> hi @qpavsmi , Can you also mark the issue as done on [unitaryhack](https://unitaryhack.dev)

Theyre supposed to have an automatic system for that, not sure why it hasnt noticed your bounty yet. Ive reached out the unitaryhack team about this.

2023-06-12 06:01 UTC, qpavsmi commented
> > hi @qpavsmi , Can you also mark the issue as done on [unitaryhack](https://unitaryhack.dev)
> 
> Theyre supposed to have an automatic system for that, not sure why it hasnt noticed your bounty yet. Ive reached out the unitaryhack team about this.

Now its marked as done in UH site

2023-06-12 06:50 UTC, AVDiv commented
> Theyre supposed to have an automatic system for that, not sure why it hasnt noticed your bounty yet. Ive reached out the unitaryhack team about this.

Yep, I too thought it works that way looks like there is an issue, anyways thank you for marking this manually.😁

2023-06-12 14:26 UTC, qpavsmi approved these changes

2023-06-12 14:49 UTC, qpavsmi commented
Merged manually, closing PR

2023-06-12 14:49 UTC, closed without merging